config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "rooms#index"
  resources :rooms, only: [:new, :create, :show, :destroy, :edit, :update] do
    resources :shift_creators, only: [:new, :create, :edit, :update]
    resources :schedules, only: [:new, :create, :show, :destroy, :edit, :update] do
      resources :shifts, only: [:index, :new, :create, :show]
    end
    member do
      get 'search'
    end
  end
  resources :users, only: [:show]
end

app/models/room.rb
class Room < ApplicationRecord
  validates :name, presence: true

  has_many :user_rooms, dependent: :destroy
  has_many :users, through: :user_rooms
  has_many :schedules, dependent: :destroy
  has_many :shift_creators, dependent: :destroy
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  validates :name, presence: true
  validates :first_day, presence: true
  validates :last_day, presence: true
  validate :date_of_terms

  belongs_to :room
  has_many :shifts, dependent: :destroy

  def self.search(search)
    if search != ""
      Schedule.where('name LIKE(?)', "%#{search}%")
    else
      Schedule.all
    end
  end

  def date_of_terms
    if first_day.present? && last_day.present?
      if first_day >= last_day 
        errors.add(:first_day)
      end
    end
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_room
  before_action :move_to_root_path
  before_action :new_move_to_root_path, only: [:new, :create]
  
  def show
    @schedule = Schedule.find(params[:id])
    @shift = Shift.find_by(user_id: current_user.id, schedule_id: @schedule.id)
    @shift_creator = ShiftCreator.find_by(room_id: params[:room_id])
  end

  def new
    @schedule = Schedule.new
  end

  def create
    @schedule = Schedule.new(schedule_params)
    if @schedule.save
      redirect_to room_path(@room.id)
    else
      render :new
    end
  end

  def destroy
    schedule = Schedule.find(params[:id])
    schedule.destroy
    redirect_to room_path(@room.id)
  end

  def edit
    @schedule = Schedule.find(params[:id])
  end

  def update
    @schedule = Schedule.find(params[:id])
    if @schedule.update(schedule_params)
      redirect_to room_path(@room.id)
    else
      render :edit
    end
  end

  private
  def schedule_params
    params
      .require(:schedule)
      .permit(:name, :first_day, :last_day)
      .merge(room_id: params[:room_id])
  end

  def set_room
    @room = Room.find(params[:room_id])
  end

  def move_to_root_path
    unless @room.user_ids.include?(current_user.id)
      redirect_to root_path
    end
  end

  def new_move_to_root_path
    @shift_creator = ShiftCreator.find_by(room_id: params[:room_id])
    unless @shift_creator.user_ids.include?(current_user.id)
      redirect_to root_path
    end
  end
  
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/edit.html.erb
<div class="contents row">
  <div class="container">
    <h2>スケジュール編集</h2>
    <div class="form-content">
      <%=form_with model: [@room, @schedule], local: true do |f| %>
        <div class="field">
          <%= f.label :スケジュール名 %>
          <%= f.text_field :name, autofocus: true, class: "form-input" %>
        </div>
        <div class="field">
          <%= f.label :シフト提出日程 %>      
        </div>
        <div class="period">
          <div class="field">
            <%= f.date_field :first_day, class: "form-shift first_date" %>
          </div>
          <div class="field last_day">
            <%= f.label :〜 %>      
            <%= f.date_field :last_day, class: "form-shift last_date" %>
          </div>
        </div>
        
        <div class="actions">
          <%= f.submit "編集" %>
        </div>
      <% end %>
    </div>
    <%= link_to room_schedule_path(@room.id, @schedule.id), class:"trash-alt-schedule", method: :delete do %>
    <% end %>
    <div class="cancel-create-room">
      <%= link_to "戻る", room_path(@room.id) %>
    </div>
  </div>
</div>  

app/views/schedules/new.html.erb
<div class="contents row">
  <div class="container">
    <h2>新規スケジュール作成</h2>
    <div class="form-content">
      <%=form_with model: [@room, @schedule], local: true do |f| %>
        <div class="field">
          <%= f.label :スケジュール名 %>
          <%= f.text_field :name, autofocus: true, class: "form-input" %>
        </div>
        <div class="field">
          <%= f.label :シフト提出日程 %>      
        </div>
        <div class="period">
          <div class="field">
            <%= f.date_field :first_day, class: "form-shift first_date" %>
          </div>
          <div class="field last_day">
            <%= f.label :〜 %>      
            <%= f.date_field :last_day, class: "form-shift last_date" %>
          </div>
        </div>
        
        <div class="actions">
          <%= f.submit "追加" %>
        </div>
      <% end %>
    </div>
    <div class="cancel-create-room">
      <%= link_to "戻る", room_path(@room.id) %>
    </div>
  </div>
</div>  

app/views/schedules/show.html.erb
<div class="schedule-wrapper">
  <div class="schedule-header">
    <% if @shift_creator.nil? %>
      <div class="shift-index">
        <%=link_to "シフト作成者を決める", new_room_shift_creator_path(@room.id)  %>
      </div>
    <% elsif @shift_creator.user_ids.include?(current_user.id) %>
      <div class="shift-index">
        <%=link_to "提出シフト一覧", room_schedule_shifts_path(@room.id, @schedule.id) %>
      </div>
    <% end %>
    <div class="schedule-title">
      <h1><%= @schedule.name %></h1>
    </div>
    <% unless @shift == nil %>
      <div class="shift-check">
        <%= link_to "提出シフトを確認する", room_schedule_shift_path(@schedule.room_id, @schedule.id, @shift.id) %>
      </div>
    <% end %>
  </div>
  <div class="schedule-main-screen-show">
   <p class="schedule-message">・・・現在シフト作成中・・・</p>
  </div>
  <div class="schedule-footer">
    <div class="schedule-footer-main"> 
      <% if @shift_creator.present? && @shift_creator.user_ids.include?(current_user.id) %>
        <div class="submit-shift">
          <%= link_to "シフトを修正する", "#" %>
        </div>
      <% end %>
      <% if @shift == nil %>
        <div class="submit-shift">
          <%= link_to "シフトを提出する", new_room_schedule_shift_path(@schedule.room_id, params[:id]) %>
        </div>
      <% end %>
    </div>
      <div class="back-to-top">
        <%= link_to "戻る", room_path(@room.id) %>
      </div>
  </div>
</div>