config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "rooms#index"
  resources :rooms, only: [:new, :create, :show, :destroy, :edit, :update] do
    resources :shift_creators, only: [:new, :create, :edit, :update]
    resources :schedules, only: [:new, :create, :show, :destroy, :edit, :update] do
      resources :shifts, only: [:index, :new, :create, :show]
    end
    member do
      get 'search'
    end
  end
  resources :users, only: [:show]
end

app/models/room.rb
class Room < ApplicationRecord
  validates :name, presence: true

  has_many :user_rooms, dependent: :destroy
  has_many :users, through: :user_rooms
  has_many :schedules, dependent: :destroy
  has_many :shift_creators, dependent: :destroy
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :destroy, :edit, :update, :search]
  before_action :move_to_index, only: [:show, :destroy, :edit, :update, :search]
  PER = 10

  def index
    if current_user.rooms.present?
      @room = current_user.rooms.limit(1)
      redirect_to room_path(@room.ids)
    end
  end
  
  def show
    @schedules = Schedule.where(room_id: params[:id]).page(params[:page]).per(PER).order(created_at: 'desc')
    @shift_creator = ShiftCreator.find_by(room_id: params[:id])
  end
  
  def new
    @room = Room.new
  end
  
  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to room_path(@room.id)
    else
      render :new
    end
  end
  
  def destroy
    @room.destroy
    redirect_to root_path
  end
  
  def edit
    @users = User.where(id: @room.user_ids)
    @shift_creator = ShiftCreator.find_by(room_id: params[:id])
  end

  def update
    if @room.update(room_params)
      redirect_to room_path(params[:id])
    else
      render :edit
    end
  end

  def search
    @schedules = Schedule.search(params[:keyword]).where(room_id: params[:id]).page(params[:page]).per(PER).order(created_at: 'desc')
  end
  
  private
  
  def room_params
    params
      .require(:room)
      .permit(:name, user_ids: [])
  end

  def set_room
    @room = Room.find(params[:id])
  end

  def move_to_index
    unless @room.user_ids.include?(current_user.id)
      redirect_to root_path
    end
  end

  
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/edit.html.erb
<div class="contents row">
  <div class="container">
  <h2>ルーム編集</h2>
  <%=form_with model: @room, local: true do |f|%>
    <div class="field">
      <%= f.label :ルーム名 %>
      <%= f.text_field :name, autofocus: true, class: "form-input" %>
    </div>
    <div class="member-select">
      <%= f.label :メンバー追加, class:"member-select-label" %>
      <div class="member">     
        <% User.where.not(id: @room.user_ids).each do |user| %>
          <div class="member-name">
            <input name="room[user_ids][]" type="checkbox" value=<%= user.id %>>
            <label for="apple" class="label"><%= user.nickname %></label>
          </div>
        <% end %>  
      </div>
      <%= f.label :現在のメンバー, class:"member-select-label" %>
        <div class="member"> 
          <% @users.each do |user|%>
            <div class="member-name">
              <input name="room[user_ids][]" type="checkbox" checked="checked" value=<%= user.id %>>
              <label for="apple" class="label"><%= user.nickname %></label>
            </div>
          <% end %>
        </div>
      </div>
    <div class="actions">
      <%= f.submit "変更" %>
    </div>
    <% if @shift_creator.present? %>
      <%= link_to edit_room_shift_creator_path(@room.id), class:"to-shift-creater" do %>
      <% end %>
    <% else %>
      <%= link_to new_room_shift_creator_path(@room.id), class:"to-shift-creater" do %>
      <% end %>
    <% end %>
    <%= link_to room_path(@room.id), class:"trash-alt", method: :delete do %>
    <% end %>
  <% end %>
</div>  

app/views/rooms/index.html.erb
<div class="wrapper">
  <div class="side-bar">
    <div class="side-bar-header">
      <div class="user-detail">
        <div class="user-image">
          <%= image_tag 'icon_sanple.png' , size: '80x80' %>
        </div>
        <div class="user-name">
          <%= link_to current_user.nickname, user_path(current_user.id) %>
        </div>
      </div>
      <div class="create-room">
       <%= link_to new_room_path, class:"bars" do %>
         <i class="far fa-bars"></i>
       <% end %>
      </div>
    </div>
    <div class="side-bar-main">
    </div>
  </div>
  <div class="shift-screen">
    <div class="shift-screen-header">
      <div class="left-header">
        <div class="header-title">
        </div>
      </div>
      <div class="main-header">
      </div>
    </div>
    <div class="shift-screen-main">
      <%= image_tag 'sanple.jpg', class:"screen-image" %>
      <div class="schedules">
      </div>
  </div>
</div>

app/views/rooms/new.html.erb
<div class="contents row">
  <div class="container">
  <h2>ルーム作成</h2>
  <%=form_with model: @room, local: true do |f|%>
    <div class="field">
      <%= f.label :ルーム名 %>
      <%= f.text_field :name, autofocus: true, class: "form-input" %>
    </div>
    <div class="member-select">
      <label class="member-select-label">メンバー選択</label>
        <div class="member">     
          <%= f.collection_check_boxes :user_ids, User.where.not(id: current_user.id), :id, :nickname do |user| %>
            <div class="member-name">
              <%= user.check_box %>
              <%= user.label {user.text} %>
            </div>
          <% end %>  
        </div>
      <input name="room[user_ids][]" type="hidden" value=<%= current_user.id %>>
    </div>
    <div class="actions">
      <%= f.submit "追加" %>
    </div>
  <% end %>
</div>  

app/views/rooms/search.html.erb
<div class="wrapper">
  <div class="side-bar">
    <div class="side-bar-header">
      <div class="user-detail">
        <div class="user-image">
          <%= image_tag 'icon_sanple.png' , size: '80x80' %>
        </div>
        <div class="user-name">
          <%= link_to current_user.nickname, user_path(current_user.id) %>
        </div>
      </div>
        <div class="create-room">
          <%= link_to new_room_path, class:"bars" do %>
          <% end %>
        </div>
      </div>
    <div class="side-bar-main">
      <div class="side-bar-rooms">
        <p class="rooms-header">ルーム</p>
        <% current_user.rooms.each do |room| %>
          <div class="room">
            <%= link_to room.name, room_path(room.id), class: "room-name" %>
            <% if @room.id == room.id %>
              <%= link_to edit_room_path(@room.id), class:"room-edit-alt" do %>
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>
      <div class="side-bar-members">
        <p class="room-users-header"><%= "#{@room.name}のメンバー" %></p>
        <% @room.users.where.not(id: current_user.id).each do |user| %>
          <div class="room-user">
            <%= link_to user.nickname, user_path(user.id), class: "room-user-name" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="shift-screen">
    <div class="shift-screen-header">
      <div class="left-header">
        <div class="header-title">
          <%= link_to @room.name , new_room_shift_creator_path(@room.id) %>
        </div>
      </div>
      <div class="main-header">
        <div class="header-search">
          <%= form_with(url: search_room_path(@room.id), method: :get, local: true, class: "search-form") do |f| %>
          <%= f.text_field :keyword, placeholder: "スケジュールを検索", class: "search-input" %>
          <%= f.submit "検索", class: "search-btn" %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="shift-screen-main">
      <%= image_tag 'sanple.jpg', class:"screen-image" %>
      <div class="schedules">
        <% @schedules.each do |schedule|%>
          <% if @room.id == schedule.room_id %>
            <div class="schedule">
              <%= link_to  room_schedule_path(@room.id, schedule.id), class: "schedule-details" do %>
                <p class="schedule-name"><%= schedule.name %></p>
                <p class="schedule-date"><%= schedule.updated_at.strftime('%Y/%m/%d %H:%M') %></p>
                <%= link_to edit_room_schedule_path(@room.id, schedule.id), class: "schedule-edit-alt" do %>
                <% end %>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
      <div class="paginate">
          <%= paginate @schedules %>
        </div>
    </div>
    <div class="main-footer">
      <div class="create-schedule" >
        <%= link_to "新規スケジュール作成", new_room_schedule_path(params[:id]) %>
      </div>
    </div>
  </div>

app/views/rooms/show.html.erb
<div class="wrapper">
  <div class="side-bar">
    <div class="side-bar-header">
      <div class="user-detail">
        <div class="user-image">
          <%= image_tag 'icon_sanple.png' , size: '80x80' %>
        </div>
        <div class="user-name">
          <%= link_to current_user.nickname, user_path(current_user.id) %>
        </div>
      </div>
        <div class="create-room">
          <%= link_to new_room_path, class:"bars" do %>
          <% end %>
        </div>
      </div>
    <div class="side-bar-main">
      <div class="side-bar-rooms">
        <p class="rooms-header">ルーム</p>
        <% current_user.rooms.each do |room| %>
          <div class="room">
            <%= link_to room.name, room_path(room.id), class: "room-name" %>
            <% if @room.id == room.id %>
              <%= link_to edit_room_path(@room.id), class:"room-edit-alt" do %>
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>
      <div class="side-bar-members">
        <p class="room-users-header"><%= "#{@room.name}のメンバー" %></p>
        <% @room.users.where.not(id: current_user.id).each do |user| %>
          <div class="room-user">
            <%= link_to user.nickname, user_path(user.id), class: "room-user-name" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="shift-screen">
    <div class="shift-screen-header">
      <div class="left-header">
        <div class="header-title">
          <%= link_to @room.name , edit_room_path(@room.id) %>
        </div>
      </div>
      <div class="main-header">
        <div class="header-search">
          <%= form_with(url: search_room_path(@room.id), method: :get, local: true, class: "search-form") do |f| %>
          <%= f.text_field :keyword, placeholder: "スケジュールを検索", class: "search-input" %>
          <%= f.submit "検索", class: "search-btn" %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="shift-screen-main">
      <%= image_tag 'sanple.jpg', class:"screen-image" %>
      <div class="schedules">
        <% @schedules.each do |schedule|%>
            <div class="schedule">
              <%= link_to  room_schedule_path(@room.id, schedule.id), class: "schedule-details" do %>
                <p class="schedule-name"><%= schedule.name %></p>
                <p class="schedule-date"><%= schedule.updated_at.strftime('%Y/%m/%d %H:%M') %></p>
              <% end %>
              <div class="schedule-edit">
                <%= link_to edit_room_schedule_path(@room.id, schedule.id), class: "schedule-edit-alt" do %>
                <% end %>
              </div>
            </div>
        <% end %>
      </div>
        <div class="paginate">
          <%= paginate @schedules %>
        </div>
    </div>
    <div class="main-footer">
      <% if @shift_creator.present? && @shift_creator.user_ids.include?(current_user.id) %>
        <div class="create-schedule" >
          <%= link_to "新規スケジュール作成", new_room_schedule_path(params[:id]) %>
        </div>
      <% end%>
    </div>
  </div>