config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "rooms#index"
  resources :rooms, only: [:new, :create, :show, :destroy, :edit, :update] do
    resources :shift_creators, only: [:new, :create, :edit, :update]
    resources :schedules, only: [:new, :create, :show, :destroy, :edit, :update] do
      resources :shifts, only: [:index, :new, :create, :show]
    end
    member do
      get 'search'
    end
  end
  resources :users, only: [:show]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShiftSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.0/css/all.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <div class="header-bar">
        <% if params[:room_id].present? %>        
          <%= link_to room_path(params[:room_id]) do %>
            <%= image_tag "title.png", class:"header-log" %>
          <% end %>
        <% elsif params[:id].present? && request.path.include?("room") %>
          <%= link_to room_path(params[:id]) do %>
            <%= image_tag "title.png", class:"header-log" %>
          <% end %>
        <% else %>
          <%= link_to root_path do %>
            <%= image_tag "title.png", class:"header-log" %>
          <% end %>
        <% end %>
        <%= link_to destroy_user_session_path, class: "header-menu-bar", method: :delete do %>
        <% end %>
      </div>
    </header>
    <%= yield %>
  </body>
</html>